### PR TITLE
fix: hide program enrollment field

### PR DESCRIPTION
**Pull request by mohsinalimat**
When hide program enrollment field then error comes.

This PR solve issue.

### CODE REVIEW

**Comment by mohsinalimat** [comment]
Anything missing in this PR?

**Comment by mohsinalimat** [comment]
@pateljannat if you are reviewer then please verify this PR?

**Review by totalys — APPROVED** [review]

**Comment by mohsinalimat** [comment]
Any update?

**Comment by mohsinalimat** [comment]
Any reviewer. please verify this PR?

**Comment by mohsinalimat** [comment]
Anyone approve this?

**Comment by pateljannat** [comment]
@mohsinalimat please add a proper description to this PR. What is the issue that this PR is trying to solve?

**Comment by mohsinalimat** [comment]
> @mohsinalimat please add a proper description to this PR. What is the issue that this PR is trying to solve?
> 
> 

@pateljannat Updated.

**Comment by mohsinalimat** [comment]
@RitvikSardana Please review.

**Comment by RitvikSardana** [comment]
@mohsinalimat 

Please update the title and description properly.

Add some screenshots, what issue you were facing and what problem does the PR Solve.

**Comment by mohsinalimat** [comment]
> what issue you were facing and what problem does the PR Solve

I already mentioned in description.

**Comment by pateljannat** [comment]
@mohsinalimat please add screenshots or videos explaining the issue as well as the fix. Also, the description that you have added is not clear. Please elaborate.

**Pull request closed without merging**
