### PR TITLE
fix: misc

### PR DESCRIPTION
**Pull request by pateljannat**
1. Converted doctypes to tab view.
2. Changed form layouts.
3. Student Applicant, Program Enrollment, and Course Enrollment will no longer be submittable.
4. Removed portal-related fields from the Program doctype.
5. After an applicant enrolls and a user is created for them, the user will automatically be linked to the Student.
6. Removed unnecessary fields from Program Enrollment.
7. Course enrollment courses will now be filtered based on the program.
8. Changed webform links from the student admission page.

### CODE REVIEW

**Comment by rtdany10** [comment]
> 3\. Student Applicant, Program Enrollment, and Course Enrollment will no longer be submittable.

@pateljannat any particular reason as to why they are changed to non-submittable doctypes?

**Comment by jigneshpshah** [comment]
`3. Student Applicant, Program Enrollment, and Course Enrollment will no longer be submittable.`

@pateljannat  because of this the Admission process has stopped !! as the old records were submittable and had docstatus =1,  now when user clicks on Application > Approve, It gives insufficient Permission error , asking for submit rights , providing submit rights is not possible as the doc is made non - submittable.  :-(


Please take in to consideration , live school sites are running on  FC on this app with develop as only branch ! 
kindly help resolve it via appropriate hot-fix patch

**Comment by pateljannat** [comment]
> It gives insufficient Permission error , asking for submit rights , providing submit rights is not possible as the doc is made non - submittable. :-(

Can you please send a recording of this?

I am unable to replicate this on my side. Does the user has the Academic User role assigned?

**Comment by rtdany10** [comment]
@jigneshpshah In you workflow, docstatus might be kept as 1 for Approved state. You can make it 0 to avoid this error.

Ideally, breaking changes shouldn't be merged to main branch as long as we don't have proper versioning.

**Comment by jigneshpshah** [comment]
Yes @rtdany10 , we did the same as of now to solve the case.

**Comment by jigneshpshah** [comment]
@pateljannat 
1. may i know the reason why _school_house_ field was removed from program enrolment ? 
2. are you planning to get it back , yes / no , so that we can plan accordingly , as the existing data of 2000 students is  affected !. Your prompt reply / fix is highly appreciated.
3. the school_house field  was important , is used to know which student was in which house in which year.

**Pull request merged**
